inherit_from: /home/shj20/unisurf/multisurf/configs/default.yaml

network:
  global_latent_dim: 32
  num_heads: 8
  num_layers: 8
  bias: 1.5
  
dataloading:
  category: toybus
  n_views: 50
  n_sample: 50
  batch_size: 1
  n_workers: 1
  resize_res: [400, 400]
  img_size: [400, 400]

training:
  out_dir: out/CO3D/0405_muti_big
  psnr_path: out/CO3D/0405_muti_big/psnr.txt
  vis_resolution: [400, 400]
  print_every: 50

UNetEncoder:
  interval: 2
model:
  depth_range: [0.5, 7.0]

rendering:
  interval_decay: 0.000010
  radius: 10
  interval_start: 4.5 
  interval_end: 0.1