inherit_from: /home/shj20/unisurf/multisurf/configs/default.yaml

network:
  global_latent_dim: 32
  num_heads: 8
  num_layers: 8
  bias: 3
  
dataloading:
  category: toybus
  n_views: 50
  n_sample: 50
  batch_size: 1
  n_workers: 1
  resize_res: [200, 200]
  img_size: [200, 200]

training:
  out_dir: out/CO3D/0405_geoinit
  psnr_path: out/CO3D/0405_geoinit/psnr.txt
  vis_resolution: [200, 200]
  print_every: 50

UNetEncoder:
  interval: 2

rendering:
  interval_decay: 0.0000015
  radius: 12