# inherit_from: configs/default.yaml
inherit_from: /home/shj20/pytorch3d/pytorch3d/implicitron/models/multisurf/configs/default.yaml

network:
  global_latent_dim: 32
  num_heads: 8
  num_layers: 8
  bias: 3
  feat_size: 256
  
dataloading:
  category: teddybear
  n_views: 70
  n_sample: 10
  batch_size: 1
  n_workers: 0
  resize_res: [200, 200]
  img_size: [200, 200]
  dataset_name: co3d_singlesequence
  load_masked_image: True
  test_on_train: False

training:
  out_dir: out/CO3D/0502_cgl_it_single
  psnr_path: out/CO3D/0502_cgl_it_single/psnr.txt
  vis_resolution: [200, 200]
  print_every: 50
  visualize_every: 1000
  use_mh_loss: True
  lambda_l1_rgb: 1.0
  lambda_normals: 0.005
  lambda_depth_diff: 0.00
  lambda_depth_loss: 0.0
  lambda_iou: 0.0002
  lambda_mh: 0.0

UNetEncoder:
  interval: 2
  #pretrained: True

model:
  depth_range: [0.3, 8]

rendering:
  interval_decay: 0.000015
  radius: 10
  interval_start: 5.0 
  interval_end: 0.3
  #render_outer_points: False